<?php
/**
 * @var $block \DavidRobert\GetRatingSummary\Block\GetRatingSummary
 */
?>

<?php
    $_ratingSummary = $block->getRatingSummary();
?>

<div class="productReviews"> <!-- closed in review list-->
    <div id="reviews" class="productReviews__container">
        <div class="block-title productReviews__title">
            <strong><?= $block->escapeHtml(__('Customer Reviews')) ?></strong>
        </div>

        <?php if($_ratingSummary){ ?>
            <div class="product-reviews-summary short">
                <div class="rating-summary">
                    <div title="<?php echo (int)$_ratingSummary; ?>%" class="rating-result">
                        <span style="width:<?php echo (int)$_ratingSummary; ?>%"><span><?php echo (int)$_ratingSummary; ?>%</span></span>
                    </div>
                </div>
            </div>
        <?php } ?>

        <div class="productReviews__basedOn">
            <span><?= $block->escapeHtml(__("Based on ")) ?></span><span><?php echo $block->getRatingCount(); ?></span><span><?= $block->escapeHtml(__(" reviews")) ?></span>
        </div>
    </div>